name: 'Joey Driscoll '
favicon: null
layout_spectrum: 0.48164
typography_spectrum: 0.70111
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121317'
    - '#feff42'
    - '#ebdbc2'
    - '#aba093'
    - '#d8453b'
  brandStrength: 0.6109132391866297
  lightness: 0.7561308578588068
  saturation: 0.9895665207877755
  rhythmicContrast: 0.02868659794330597
purpose: []
